version: '3.8'

services:
  web:
    build: .
    command: bash -c "bundle exec rails server -b '0.0.0.0'"
    volumes:
      - ".:/rails" 
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydb
      - RAILS_ENV=development
    entrypoint: ["./bin/docker-entrypoint"]

  db:
    image: postgres:13
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mydb

volumes:
  postgres_data:
    driver: local
